version: "3"
services:
  zshop-gateway:
    container_name: zshop-gateway
    image: zshop-gateway
    depends_on:
      - zshop-auth
      - zookeeper-1
      - zookeeper-2
      - kafka-1
      - kafka-2
    build: ./zshop-gateway
    ports:
      - "8000:8000"
  zshop-auth:
    container_name: zshop-auth
    image: zshop-auth
    depends_on:
      - zshop-auth-postgres
      - zookeeper-1
      - zookeeper-2
      - kafka-1
      - kafka-2
    build: ./zshop-auth
    ports:
      - "9000:9000"
  zshop-auth-postgres:
    container_name: zshop-auth-postgres
    image: postgres
    env_file:
      - ./zshop-user/.env
    ports:
      - "54329:5432"
    volumes:
      - ./zshop-auth/pgdata:/var/lib/postgresql/data
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "12181:2181"
  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - "19092:19092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-1
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:1181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafka-2:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka-2
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:1181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1